const express = require('express')
const app = express()
const port = 3000
const path = require('path')
const http = require('http').createServer(app)
const io = require('socket.io')(http)

const Room = require('./gameRoundClasses/gameRoundClass')

app.use('/', express.static(path.join(__dirname, '../dist')))

app.get('/*', (req, res) => {
    res.sendFile(path.join(__dirname, '../dist/index.html'))
})

let state = {
    rooms: {
        // room1: {
        //     //<--This key is generated by user
        //     lettersNotPlayedSoFar: ['a', 'b', 'c'],
        //     players: {
        //         muin: {
        //             //<--This key is generated by user
        //             socketId: '<   socket.id stored here   >',
        //             wordsPlayed: [
        //                 ['apple', 'august', 'Applebees'],
        //                 ['beef', 'Ben', 'Baskin Robbins'],
        //             ],
        //             points: 17,
        //         },
        //     },

        //     currentWordsInRound: {
        //         muin: ['catfish', 'Charles Boyle', 'Carvel'],
        //     },
        // },
    },
}

const getListOfRooms = () => Object.keys(state.rooms)

const joinRoom = () => {}

io.on('connection', clientSocket => {
    console.log('a user connected')
    clientSocket.on('disconnect', () => {
        console.log('user disconnected')
    })
    clientSocket.on('hello', string => {
        console.log('Received a hello on server side')
        clientSocket.emit('ping', {payload: 'yo'})
    })
})

http.listen(port, () => console.log(`App listening on port ${port}!`))
